php-api:
  build: .
  environment:
    ENV: 'dev'
  container_name: php-api
  command: sh /srv/scripts/post_install_api.sh
  volumes:
    - ./:/srv
  working_dir: /srv/api
  ports:
    - 80:80
  links:
    - mysql
mysql:
  image: mysql:latest
  container_name: mysql-api
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: my-secret-pw
    MYSQL_DATABASE: 'todoapi'
    MYSQL_USER: 'api_user'
    MYSQL_PASSWORD: 'api_user'